name: branch-name-validator

on: [pull_request]

jobs:
  check-jira-prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(no-ticket/|renovate[-/]|hotfix/|FRI-[0-9]+/|dependabot/)' # start branch with either 'no-ticket/' or 'FRI-NUMBER/', allowing for bots and hotfixes
          ignore: main
